vich_uploader:
    db_driver: orm
    mappings:
        tune_files:
            uri_prefix:         "%app.path.tune_file_path%"
            upload_destination: "%app.upload.destination%"
            namer:              vich_uploader.namer_uniqid